export const GET_CART_LOADING = "GET_CART_LOADING";
export const GET_CART_SUCCESS = "GET_CART_SUCCESS";
export const GET_CART_ERROR = "GET_CART_ERROR";

export const ADD_CART_LOADING = "ADD_CART_LOADING";
export const ADD_CART_SUCCESS = "ADD_CART_SUCCESS";
export const ADD_CART_ERROR = "ADD_CART_ERROR";